# Generated by Django 5.1.5 on 2025-02-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
